spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_social_network
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost #where the smtp server is running
    port: 1025
    username: ben@gmail.com
    password: ben
    properties:
      mail:
        smtp:
          starttls:
            enable: false
            required: false
          trust: "*"
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      host: localhost
      port: 1025

application:
  security:
    jwt:
      secret-key: 846914419DDF25C16E8F341FA5A8C25C16E8F341FA14419DDF25C16E8
      expiration: 86_400_000
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account/